name: firstcalc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  math_expressions: ^2.6.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
